from pydantic import BaseModel, Field
from typing import Generic, TypeVar, Optional, List, Any

T = TypeVar("T")

# Unified Response Envelopes
class StandardResponse(BaseModel, Generic[T]):
    success: bool = True
    message: str = "Request completed successfully"
    data: Optional[T] = None

class ErrorDetail(BaseModel):
    code: str
    details: Optional[Any] = None

class StandardErrorResponse(BaseModel):
    success: bool = False
    message: str
    error: ErrorDetail

# Chat API Schemas
class Message(BaseModel):
    role: str = Field(..., description="Role of the message author (e.g. system, user, assistant)")
    content: str = Field(..., description="The content of the message")

class ChatRequest(BaseModel):
    messages: List[Message] = Field(..., min_length=1, description="List of chat messages representing conversation history")
    provider: Optional[str] = Field(None, description="AI Provider to use (falls back to configured default)")
    model: Optional[str] = Field(None, description="AI Model to use (falls back to configured default)")
    temperature: Optional[float] = Field(0.7, ge=0.0, le=2.0, description="Sampling temperature")

class ChatResponseData(BaseModel):
    message: Message = Field(..., description="The response message generated by the AI model")
    provider: str = Field(..., description="The provider that generated the response")
    model: str = Field(..., description="The model used to generate the response")
